/*This is a port configuration file generated by python script*/
/* To use this file, first update a PORT_CONFIG.txt and run the script*/
Port_init()
{
	Port_mode (PORT0,1,FUNCTION0);
	Port_mode (PORT0,2,FUNCTION0);
	Port_mode (PORT0,23,FUNCTION1 
);
}